name: Golang CI
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install api_gen
        run: |
          GOROOT=$(pwd)/bin go get -u golang.org/x/tools/cmd/goimports
          GOROOT=$(pwd)/bin go get -u github.com/go-generalize/api_gen/server_generator
      - name: Execute api_gen
        run: ../bin/server_generator ./controller
        working-directory: api
      - uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=../.github/.golangci.yml"
          workdir: api
